### ISSUE TITLE
Changes review

### ISSUE THREAD

**Issue by LizaTretyakova-zz** [eabatalov/spbau-data-backup#4]
To make debug version: make debug
To run under valgrind: make mem_check
To run on the test: make; bin//main <folder_name>

Changes are made in this period: https://github.com/eabatalov/spbau-data-backup/compare/9079510a8977a503b487857ab961c5ef8f86ad26...3206f66

**Comment by eabatalov** [comment]
1. Don't copy paste debug and release Makefile rules. Use different CFLAGS for debug and release targets.
2. Remove mem_check target from Makefile. mem_check is part of testing code. Put dedicated shell/python script for running tests under valgrind to test/src directory. test Makefile should copy it to test/bin.
3. I see some misunderstanding of projects structure. Let me repeat it.
   src/ - code of library (no main() function there)
   Makefile - makefile that builds library .so and .a files
   include/ - dir for library interface headers
   bin/debug - debug build of library
   bin/release - release build of library
   test/src - source files of tests (include main() function, scripts, etc)
   test/bin - binary files of test
   test/Makefile - makefile for tests. build test/src/*.c files put them to test/bin/, copy scripts to bin. Use debug CFLAGS on test build, link with debug version of library.
4. I don't understand current directory structure. Why it was structured this way. And where I can find library and where I can find tests (looks like some sources are mixed with each other).

**Comment by eabatalov** [comment]
/include/file_tree_nodes.h
Move this to internal lib headers:
 11 #define ANSI_COLOR_RED "\x1b[31m"
 12 #define ANSI_COLOR_GREEN "\x1b[32m"
 13 #define ANSI_COLOR_YELLOW "\x1b[33m"
 14 #define ANSI_COLOR_BLUE "\x1b[34m"
 15 #define ANSI_COLOR_MAGENTA "\x1b[35m"
 16 #define ANSI_COLOR_CYAN "\x1b[36m"
 17 #define ANSI_COLOR_RESET "\x1b[0m"

**Comment by eabatalov** [comment]
Leave only public interface declarations in /include/file_tree_nodes.h

**Comment by eabatalov** [comment]
Merge debug and release targets in all Makefiles.

Example of conditional logic:
ifneq ($(KERNELRELEASE),)
    obj-m := $(MOD_NAME).o
    header-y += mutex_ioctl.h kernel_spinlock.h
    $(MOD_NAME)-objs := module.o
else
    include ../sub_config.mk

Need to use CFLAGS, RELEASE_FLAGS, DEBUG_FLAGS.

**Comment by eabatalov** [comment]
Add bin/\* to .gitignore file
do
git rm -r bin/*

**Comment by eabatalov** [comment]
Add definitions of FS nodes and tree to lib interface header.

**Comment by eabatalov** [comment]
Ok. Continue review after our work on the project.

Please
git rm -r library/
nothing interesting here.

Please remove not needed include directives such as
  4 #include <sys/types.h>
  5 #include <sys/stat.h>
  6 #include <unistd.h>
  7 #include <stdio.h>
  8 #include <dirent.h>
  9 #include <stdlib.h>
from include/fs_tree.h

**Comment by LizaTretyakova-zz** [comment]
I can see no library/ . Is it okay?

**Comment by eabatalov** [comment]
It's ok I've checked. ignore library comment.

**Comment by eabatalov** [comment]
file_tree_nodes.h should include fs_tree.h as it requires definitions from it.
Remove
 12 struct inode;
 13 struct regular_file_inode;
 14 struct dir_inode;
 15 struct fs_tree;
as it just duplicates declarations from fs_tree.h

Forward declarations such as struct node are used only in special cases where a little dependency or compilation time hacking is needed. They are not used in regular cases.

**Comment by eabatalov** [comment]
file_tree.c is better to be renamed to inodes.c

**Comment by eabatalov** [comment]
What if we've passed not directory path?

  6 struct fs_tree\* fs_tree_collect(const char\* path) {
  7     struct fs_tree\* tree = (struct fs_tree_)malloc(sizeof(struct fs_tree
  8     struct dir_inode_ tmp_to_get_tree_head = (struct dir_inode_)malloc(s
  9     if(!tmp_to_get_tree_head) {
 10         perror("Error: failed to allocate memory");
 11         exit(1);
 12     }
 13     init_dir_inode(tmp_to_get_tree_head, path, NULL);
 14     tree->head = &(tmp_to_get_tree_head->inode);
 15     build_file_tree((struct dir_inode_)(tree->head));
 16 
 17     return tree;
 18 }

FS tree may contain only one not directory inode.

**Comment by eabatalov** [comment]
I think we need to add more structure to internal library implementation.
Let's create the following internal modules for our library:
1.
inodes.c - implement initialization/deinitialization of inode, regular_file_inode, dir_inode
inodes.h - decalres functions for initialization/deinitialization of regular_file_inode anddir_inode. inode initialization and deinitialization functions are not exported (declared) in this header.

2.
fs_tree.c - implements fs_tree_collect, fs_tree_destroy, fs_tree_print

3.
dfs.c - implements fs_tree_dfs

4.
bfs.c - implements fs_tree_bfs

fs_tree.c, dfs.c, bfs.c implement public library interface functions and don't introduce any internal library interface functions.

inodes.c doesn't implement any public library interface but introduce new internal library interfaces. Include  inodes.h at least in fs_tree.c

Remove copy-paste in init_reg_file_inode, init_dir_inode and corresponding deinitialization functions due to introduction of inode initialization/deinitialization functions and call of them in init_reg_file_inode, init_dir_inode and corresponding deinit functions.

**Comment by eabatalov** [comment]
As (for now) fs_diff is a tool not a library I don't see any reason to have include/fs_diff.h.
I would probably make a library out of this tool but that'll be later and it is not 100%.

**Comment by eabatalov** [comment]
Please close this issue after you've done wit it.
