### ISSUE TITLE
 Print all the added and deleted files in FS tree Y comparing to some FS tree X

### ISSUE THREAD

**Issue by eabatalov** [eabatalov/spbau-data-backup#5]
Create new app fs_diff in root of repository.
Use fs_tree library as a source of FS tree information.

**Comment by LizaTretyakova-zz** [comment]
Check me, please!

**Comment by eabatalov** [comment]
Please rename directory collect_file_tree to libfstree

**Comment by eabatalov** [comment]
Cool. You've extracted init_inode, deinit_inode functions and made inodes.c and fs_tree.c.
But we also need separate header files for each internal fs_tree library .c file. Having single inodes.h with all the functions is bad.

Looks like each inode type has a lot of code. So it is better to create dedicated .c and .h files for each inode type. (dir_inode is especially complicated). We'll do it later.

This parameters need to be packed into something like bfs_state struct:
 16 void dir_bfs(fs_tree_inode_visitor visit, void\* data, struct inode\* queue[],
 17                 int\* queue_start, int\* queue_end, int\* running) {

About tests:
collect_file_tree.c and first_test.c doesn't say "OK" or "NOT OK". So they are not good tests. Also names of collect_file_tree.c and first_test.c files don't relate to actual things happening in the tests.

**Comment by eabatalov** [comment]
Reviewing fs_diff tool.

CAT! X-D
Err:lengths of the given directories should be equal :3

Actually there should be no restrictions on dir names. We should be able to compare any file trees.

Difference of root inode names don't imply difference of whole trees:
 64     if(strcmp(old->head->name, new->head->name) != 0
 65             || old->head->type != new->head->type){
 66         printf("deleted:\n");
 67         fs_tree_print(old);
 68         printf("added:\n");
 69         fs_tree_print(new);
 70         return;
 71     }

This naming is bad:
int it = is_in_tree
is_in_tree returns bool (by its name).
but it returns index or -1. Index is written to it not ix var.

**Comment by eabatalov** [comment]
I'll leave this task opened as TODO work for the project.
